version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      aws:
        patterns:
          - "github.com/minio/minio-go/v7"
          - "github.com/minio/minio-go/v7/pkg/credentials"
          - "github.com/redis/go-redis/v9"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
